### ISSUE TITLE
Warning ! Login and Password in the script

### ISSUE THREAD

**Issue by ghost** [craigmartell/OmniFocus2Todoist#1]
Thank you for these scripts. Becarefull, in the file `OmniFocus2Todoist.py`, there is your _Todoist_ login and password !
You should replace them by something like *****.

**Comment by craigmartell** [comment]
Wow. Great catch. Will fix immediately. Thx.

**Comment by craigmartell** [comment]
Good thing I use randomly generated passwords :-).

**Comment by craigmartell** [comment]
Changes made: Removed hard-coded username and password.  Now code prompts user for Username and Password.
